Handle errors if directories don't exist

diff --git a/scripts/settemp b/scripts/settemp
--- a/scripts/settemp
+++ b/scripts/settemp
@@ -33,6 +33,10 @@ if ! [[ "${1}" =~ $re ]] ; then
   echo "ERROR: Setpoint must be a number" >&2; exit 1
 fi
 
+if [[ ! -d ${DIR} ]]; then
+  echo "ERROR: Specified working directory ${DIR} does not exist - cannot create setpoint file" >&2; exit 1
+fi
+
 # Write new setpoint to setpoint file
 echo "${1}" >  "$DIR/setpoint"
 read setpoint <  "$DIR/setpoint"
@@ -40,5 +44,8 @@ datestr="$(date +"%F-%T:")"
 # If log is specified in config file, output to log as well as STDOUT
 if [[ ! -z "${ControllerLogfile}" ]]; then
   echo "$datestr Setpoint: $setpoint" >>  "${ControllerLogfile}"
+  if [[ $? -ne 0 ]]; then
+    echo "WARNING: Cannot open / write to logfile ${ControllerLogfile} - check filename is correct and permissions?"
+  fi
 fi
 echo "$datestr Setpoint: $setpoint"
